### PR TITLE
Implement streaming writers

### PR DESCRIPTION
**Pull request by xamgore**
Discussion at #763.

- This work took ~2 days. I've reviewed writer tests several times. Reader wasn't touched, I guess that's ok.
- The main idea is that you have to create `xml::writer::EventEmitter` once, and pass it here and there between nodes.
- As putting bytes into a stream is potentially fallible operation (disk, network may fail), all `build_to` methods return `Result`.
- There are special helpers like `apply`, `apply_if`, `apply_each`, `apply_opt`, `add_child`, `add_children` that allow chaining the commands. They also return `Result`, thus all those questions `?` in the code.

The naming is not the best, probably something like “produce” would sound better, but I leave this up to you.

The final step is making `BuildXML` trait public. `#[hidden(doc)]` may also be helpful here, to hide the methods from IDE and [docs.rs](docs.rs).

### CODE REVIEW

**Comment by xamgore** [comment]
@bokuweb if the source code looks ok, give me a note, I'll then proceed with js tests.

**Comment by bokuweb** [comment]
@xamgore It looks good. The line breaks in the output XML have changed, but the data structure itself doesn’t appear to have been modified. If that’s the case, please run cd docx-wasm && npm run test -- --updateSnapshot to update the snapshot.

**Comment by xamgore** [comment]
Many thanks! I'm not sure, whether indentation spaces and new lines are somehow useful. Except for tests, of course. So there is an option to turn them off. May try in one of the following PRs.

**Comment by xamgore** [comment]
I'm getting some weird messages from npm v10, node v20. Could you please help with the branch?

<details><summary>Details</summary>
<p>

image
image

</p>
</details>

**Comment by xamgore** [comment]
The branch needs rebasing on master. That's going be a nightmare 😬. Will do it, as well as updating snapshots.

**Comment by xamgore** [comment]
Ok, I was missing `wasm-pack`.

- After running nodejs tests, it turned out there was a small indexing bug, `refId0` instead of `refId1`. Fixed.
- Have decided to drop XML pretty formatting, and leave snapshots the way they were before. Everything is fine.
- Fixed clippy warnings
- Rebased on master

If this is possible, I would merge the branch as soon as possible to avoid further conflicts. Not sure what to do with `v0.5` branch, though. Could probably migrate it too.

**Comment by xamgore** [comment]
regviz:

```
Failed to find run Error: Command 'git' failed with args 'merge-base -a 89b08e235ada133e8c1631d676f93a231a7330b7
 31d7030d324eaf153ce1a8f66977159e8d28c73a': fatal: Not a valid commit name 
 31d7030d324eaf153ce1a8f66977159e8d28c73a
: Error: The process '/usr/bin/git' failed with exit code 128
    at /home/runner/work/_actions/reg-viz/reg-actions/v2/lib/git.js:36:1
    at Generator.throw (<anonymous>)
    at rejected (/home/runner/work/_actions/reg-viz/reg-actions/v2/lib/git.js:6:1)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by bokuweb** [comment]
@xamgore Ok, please ignore for now. I'll fix it.
Thanks for great work. Looks good.

**Comment by bokuweb** [comment]
@xamgore 0.4.18-rc19 published

**Pull request merged**
