### PR TITLE
Support for Paragraph's Line Spacing

### PR DESCRIPTION
**Pull request by lkadalski**
## What does this change?

This change provides a possibility to set line spacing in a paragraph as mentioned in [ticket](https://github.com/bokuweb/docx-rs/issues/328) 
Two extra settings are provided:
* `Before`
* `After`
Beside user is able to set spacing type: `atLeast`, `exact` or `auto` with a reference value `line`.
I extracted some code from `Spacing` type and renamed it as `CharacterSpacing` which is more clear for me.
From now there are two Spacing types: Line and Character. 
 
## References
I used mainly dotnet specification for docx. 
https://docs.microsoft.com/en-us/dotnet/api/documentformat.openxml.wordprocessing.linespacingrulevalues

### CODE REVIEW

**Comment by bokuweb** [comment]
@lkadalski Thanks for your great work, and sorry for late about #343. I'll do it.

Looks good.

Could you please check `clippy` error.

Then update snapshot testing following command, please.

- docx-core

```
cargo-insta review
```

And could you please check `docx-wasm`  test.

```
cd docx-wasm && yarn install && yarn test
```

**Comment by lkadalski** [comment]
I'm working on this `wasm` ;) Let's see...

**Comment by lkadalski** [comment]
With updated clippy there were more things to fix. I applied the fixes, but they were in random locations. Mainly related to double reference or using `mem::replace` instead of better `mem::take`

**Review by bokuweb — APPROVED** [review]
LGTM 🎉

**Comment by bokuweb** [comment]
0.2.14 published

**Comment by lkadalski** [comment]
Thanks, great news :+1:

**Pull request merged**
